import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, Dialog, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Pagination, Paper, Select, Skeleton, Stack, Tab, Tabs, Typography } from "@mui/material";
import NotificationsActiveOutlinedIcon from "@mui/icons-material/NotificationsActiveOutlined";
import Inventory2OutlinedIcon from "@mui/icons-material/Inventory2Outlined";
import CloudDoneOutlinedIcon from "@mui/icons-material/CloudDoneOutlined";
import DoneAllOutlinedIcon from "@mui/icons-material/DoneAllOutlined";
import OpenInNewOutlinedIcon from "@mui/icons-material/OpenInNewOutlined";
import { useNavigate } from "react-router-dom";
import { notificationsApi } from "../../api/notifications";
import type { Notification, NotificationFilters, NotificationPriority, NotificationType } from "../../types/notification";

const initial: NotificationFilters = { page: 1, limit: 20 };
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (x) => x.toUpperCase());
const relative = (value: string) => { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return "Just now"; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86400)}d ago`; };
const priorityColor: Record<NotificationPriority, "default" | "info" | "warning" | "error"> = { LOW: "info", MEDIUM: "warning", HIGH: "warning", CRITICAL: "error" };
const typeIcon = (type: NotificationType) => type.includes("IMPORT") ? <CloudDoneOutlinedIcon /> : type.includes("STOCK") || type === "OVERSTOCK" ? <Inventory2OutlinedIcon /> : <NotificationsActiveOutlinedIcon />;

export default function NotificationsPage() {
  const [filters, setFilters] = useState<NotificationFilters>(initial);
  const [selected, setSelected] = useState<Notification | null>(null);
  const client = useQueryClient(); const navigate = useNavigate();
  const list = useQuery({ queryKey: ["notifications", filters], queryFn: () => notificationsApi.list(filters), refetchInterval: 15000 });
  const refresh = () => { client.invalidateQueries({ queryKey: ["notifications"] }); client.invalidateQueries({ queryKey: ["notification-unread-count"] }); };
  const read = useMutation({ mutationFn: notificationsApi.markRead, onSuccess: (item) => { setSelected(item); refresh(); } });
  const readAll = useMutation({ mutationFn: notificationsApi.markAllRead, onSuccess: refresh });
  const update = <K extends keyof NotificationFilters>(key: K, value: NotificationFilters[K] | undefined) => setFilters((current) => ({ ...current, [key]: value, page: 1 }));
  const open = (item: Notification) => { setSelected(item); if (!item.is_read) read.mutate(item.id); };
  const destination = (item: Notification) => item.resource_type === "Product" ? "/products" : item.resource_type === "DataImport" ? "/data-import" : null;
  return <Box sx={{ maxWidth: 1180, mx: "auto" }}>
    <Paper elevation={0} sx={{ p: { xs: 2.5, sm: 4 }, mb: 2.5, borderRadius: 4, color: "common.white", background: "linear-gradient(115deg,#172554,#312e81 58%,#0f766e)" }}>
      <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={2} alignItems={{ sm: "center" }}><Box><Typography variant="overline" sx={{ opacity:.75, letterSpacing:1.8 }}>NOTIFICATION CENTER</Typography><Typography variant="h4" fontWeight={800}>Stay ahead of your business</Typography><Typography sx={{ mt:.75, opacity:.85 }}>Inventory, import and important operational alerts update automatically every 15 seconds.</Typography></Box><Button color="inherit" variant="outlined" startIcon={<DoneAllOutlinedIcon />} disabled={!list.data?.items.some((x) => !x.is_read) || readAll.isPending} onClick={() => readAll.mutate()} sx={{ borderColor:"rgba(255,255,255,.45)", whiteSpace:"nowrap" }}>Mark all as read</Button></Stack>
    </Paper>
    <Paper sx={{ p:2, borderRadius:3, mb:2.5 }}><Stack direction={{ xs:"column", md:"row" }} gap={1.5} alignItems={{ md:"center" }}><Tabs value={filters.is_read === undefined ? "all" : filters.is_read ? "read" : "unread"} onChange={(_, value) => update("is_read", value === "all" ? undefined : value === "read")}><Tab value="all" label="All"/><Tab value="unread" label="Unread"/><Tab value="read" label="Read"/></Tabs><Box sx={{ flexGrow:1 }}/><FormControl size="small" sx={{ minWidth:175 }}><InputLabel>Type</InputLabel><Select label="Type" value={filters.notification_type ?? ""} onChange={(e) => update("notification_type", (e.target.value || undefined) as NotificationType | undefined)}><MenuItem value="">All types</MenuItem>{["OUT_OF_STOCK","STOCKOUT_RISK","LOW_STOCK","OVERSTOCK","IMPORT_COMPLETED","IMPORT_FAILED","SALES_ALERT","SYSTEM_ALERT"].map((x) => <MenuItem key={x} value={x}>{title(x)}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{ minWidth:140 }}><InputLabel>Priority</InputLabel><Select label="Priority" value={filters.priority ?? ""} onChange={(e) => update("priority", (e.target.value || undefined) as NotificationPriority | undefined)}><MenuItem value="">All priorities</MenuItem>{["CRITICAL","HIGH","MEDIUM","LOW"].map((x) => <MenuItem key={x} value={x}>{title(x)}</MenuItem>)}</Select></FormControl></Stack></Paper>
    {list.isError ? <Alert severity="error">Notifications could not be loaded. Please try again.</Alert> : list.isLoading ? <Paper sx={{ p:2 }}><Skeleton height={90}/><Skeleton height={90}/><Skeleton height={90}/></Paper> : !list.data?.items.length ? <Paper sx={{ p:7, borderRadius:3, textAlign:"center" }}><NotificationsActiveOutlinedIcon color="primary" sx={{ fontSize:52 }}/><Typography variant="h6" mt={1}>You're all caught up.</Typography><Typography color="text.secondary">No notifications match these filters.</Typography></Paper> : <Stack gap={1.25}>{list.data.items.map((item) => <Paper key={item.id} onClick={() => open(item)} sx={{ cursor:"pointer", p:2, borderRadius:3, borderLeft:"5px solid", borderColor: item.is_read ? "divider" : item.priority === "CRITICAL" ? "error.main" : item.priority === "HIGH" ? "warning.main" : "primary.main", bgcolor:item.is_read ? "background.paper" : "action.hover", transition:".15s", "&:hover": { transform:"translateY(-1px)", boxShadow:3 } }}><Stack direction="row" gap={1.75} alignItems="flex-start"><Box sx={{ p:1, color:"primary.main", display:"grid", placeItems:"center" }}>{typeIcon(item.type)}</Box><Box sx={{ flexGrow:1, minWidth:0 }}><Stack direction={{ xs:"column", sm:"row" }} justifyContent="space-between" gap={.5}><Typography fontWeight={item.is_read ? 600 : 800}>{item.title}</Typography><Typography variant="caption" color="text.secondary">{relative(item.created_at)}</Typography></Stack><Typography color="text.secondary" sx={{ mt:.35 }}>{item.message}</Typography><Stack direction="row" gap={.75} mt={1} flexWrap="wrap"><Chip size="small" label={title(item.type)} variant="outlined"/><Chip size="small" label={title(item.priority)} color={priorityColor[item.priority]} />{item.resource_type && <Chip size="small" label={item.resource_type}/>} {!item.is_read && <Chip size="small" label="New" color="primary"/>}</Stack></Box></Stack></Paper>)}</Stack>}
    {!!list.data?.total_pages && list.data.total_pages > 1 && <Box display="flex" justifyContent="center" mt={3}><Pagination count={list.data.total_pages} page={filters.page} onChange={(_, page) => setFilters((x) => ({...x,page}))}/></Box>}
    <Dialog open={!!selected} onClose={() => setSelected(null)} maxWidth="sm" fullWidth><DialogTitle>{selected?.title}</DialogTitle><DialogContent dividers>{selected && <Stack gap={2}><Typography>{selected.message}</Typography><Stack direction="row" gap={1}><Chip label={title(selected.type)} variant="outlined"/><Chip label={title(selected.priority)} color={priorityColor[selected.priority]}/></Stack>{selected.payload && <Paper variant="outlined" sx={{ p:2, bgcolor:"action.hover" }}><Typography fontWeight={700} mb={1}>Alert details</Typography>{Object.entries(selected.payload).map(([key,value]) => <Stack key={key} direction="row" justifyContent="space-between" gap={2}><Typography color="text.secondary">{title(key)}</Typography><Typography fontWeight={600}>{String(value ?? "—")}</Typography></Stack>)}</Paper>}{destination(selected) && <Button variant="contained" endIcon={<OpenInNewOutlinedIcon/>} onClick={() => { navigate(destination(selected)!); setSelected(null); }}>View {selected.resource_type}</Button>}</Stack>}</DialogContent></Dialog>
  </Box>;
}