from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    COMPANY_ADMIN = "COMPANY_ADMIN"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class AuditAction(str, Enum):
    COMPANY_REGISTERED = "COMPANY_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
    USER_LOGOUT = "USER_LOGOUT"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"

    # Category Management
    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    CATEGORY_DELETED = "CATEGORY_DELETED"

    # Product Management
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"
    PRODUCT_ACTIVATED = "PRODUCT_ACTIVATED"
    PRODUCT_DEACTIVATED = "PRODUCT_DEACTIVATED"

    # Sales Management
    SALE_CREATED = "SALE_CREATED"
    SALE_UPDATED = "SALE_UPDATED"
    SALE_DELETED = "SALE_DELETED"
    INVENTORY_UPDATED = "INVENTORY_UPDATED"
    PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK"

    # Inventory Management
    STOCK_ADDED = "STOCK_ADDED"
    STOCK_REMOVED = "STOCK_REMOVED"
    STOCK_ADJUSTED = "STOCK_ADJUSTED"
    CUSTOMER_REGISTERED = "CUSTOMER_REGISTERED"
    CUSTOMER_VIP = "CUSTOMER_VIP"
    CUSTOMER_FIRST_PURCHASE = "CUSTOMER_FIRST_PURCHASE"
    REORDER_LEVEL_UPDATED = "REORDER_LEVEL_UPDATED"
    PRODUCT_LOW_STOCK = "PRODUCT_LOW_STOCK"

    # Analytics Dashboard
    DASHBOARD_VIEWED = "DASHBOARD_VIEWED"
    DASHBOARD_FILTERS_APPLIED = "DASHBOARD_FILTERS_APPLIED"
    REPORT_EXPORTED = "REPORT_EXPORTED"

    # Demand forecasting
    FORECAST_GENERATED = "FORECAST_GENERATED"
    FORECAST_EXPORTED = "FORECAST_EXPORTED"
    FORECAST_REFRESHED = "FORECAST_REFRESHED"
    INVENTORY_RECOMMENDATION_GENERATED = "INVENTORY_RECOMMENDATION_GENERATED"

    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"
    CUSTOMER_DELETED = "CUSTOMER_DELETED"
    CUSTOMER_ACTIVATED = "CUSTOMER_ACTIVATED"
    CUSTOMER_DEACTIVATED = "CUSTOMER_DEACTIVATED"
    CUSTOMER_EXPORTED = "CUSTOMER_EXPORTED"


class CategoryStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class ProductStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class UnitOfMeasure(str, Enum):
    PCS = "PCS"
    KG = "KG"
    GRAM = "GRAM"
    LITRE = "LITRE"
    ML = "ML"
    BOX = "BOX"
    PACK = "PACK"
    DOZEN = "DOZEN"
    METER = "METER"
    UNIT = "UNIT"


class SalesChannel(str, Enum):
    RETAIL_STORE = "RETAIL_STORE"
    ONLINE_STORE = "ONLINE_STORE"
    MARKETPLACE = "MARKETPLACE"


class PaymentMethod(str, Enum):
    CASH = "CASH"
    CARD = "CARD"
    UPI = "UPI"
    BANK_TRANSFER = "BANK_TRANSFER"


class NotificationType(str, Enum):
    LOW_STOCK = "LOW_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    STOCK_ADJUSTED = "STOCK_ADJUSTED"
    CUSTOMER_REGISTERED = "CUSTOMER_REGISTERED"
    CUSTOMER_VIP = "CUSTOMER_VIP"
    CUSTOMER_FIRST_PURCHASE = "CUSTOMER_FIRST_PURCHASE"
    FORECAST_ALERT = "FORECAST_ALERT"


class StockStatus(str, Enum):
    IN_STOCK = "IN_STOCK"
    LOW_STOCK = "LOW_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"


class AdjustmentType(str, Enum):
    """Input type for a manual stock adjustment request."""

    STOCK_IN = "STOCK_IN"
    STOCK_OUT = "STOCK_OUT"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"


class MovementType(str, Enum):
    """Type recorded against each row of stock movement history."""

    SALE = "SALE"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
    STOCK_ADDITION = "STOCK_ADDITION"
    STOCK_REMOVAL = "STOCK_REMOVAL"
